# Generated by Django 5.0.7 on 2024-08-17 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_perfil_telefono_alter_perfil_pagina_web'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='pagina_web',
        ),
        migrations.AlterField(
            model_name='perfil',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='perfil_imagenes/'),
        ),
    ]
